// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu9J5jgMndPPTlWGl6W8xjxshZTuPl7Qw',
    appId: '1:969245355476:web:417a819dd767425d263a41',
    messagingSenderId: '969245355476',
    projectId: 'agrivision-7d3af',
    authDomain: 'agrivision-7d3af.firebaseapp.com',
    storageBucket: 'agrivision-7d3af.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1jE6jVTiCLGDgbTcW1svM78fRgFE8ICo',
    appId: '1:969245355476:android:7366802197c5a8fe263a41',
    messagingSenderId: '969245355476',
    projectId: 'agrivision-7d3af',
    storageBucket: 'agrivision-7d3af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAdAwz3msgmhRtPeuycWZ-Z3UvY5ewdOc',
    appId: '1:969245355476:ios:7b49886f68d01624263a41',
    messagingSenderId: '969245355476',
    projectId: 'agrivision-7d3af',
    storageBucket: 'agrivision-7d3af.firebasestorage.app',
    iosBundleId: 'com.example.agrivision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAdAwz3msgmhRtPeuycWZ-Z3UvY5ewdOc',
    appId: '1:969245355476:ios:7b49886f68d01624263a41',
    messagingSenderId: '969245355476',
    projectId: 'agrivision-7d3af',
    storageBucket: 'agrivision-7d3af.firebasestorage.app',
    iosBundleId: 'com.example.agrivision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu9J5jgMndPPTlWGl6W8xjxshZTuPl7Qw',
    appId: '1:969245355476:web:bf7dfefd2ec272af263a41',
    messagingSenderId: '969245355476',
    projectId: 'agrivision-7d3af',
    authDomain: 'agrivision-7d3af.firebaseapp.com',
    storageBucket: 'agrivision-7d3af.firebasestorage.app',
  );
}
